### ISSUE TITLE
no such target '@com_github_grpc_ecosystem_grpc_gateway//runtime:runtime'

### ISSUE THREAD

**Issue by titanous** [bazelbuild/bazel-gazelle#892] opened 2020-08-31 17:48 UTC
### What version of gazelle are you using? 

0.22.0

### What version of rules_go are you using?

0.24.0

### What version of Bazel are you using?

3.4.1

### Does this issue reproduce with the latest releases of all the above?

Yes, and this specific error does not occur on v0.21.1.

### What operating system and processor architecture are you using?

Linux 5.4.40 (Debian Buster) x86_64

### What did you do?

```
bazel run @com_github_bmeg_grip//:grip
```

See: https://github.com/titanous/gazelle-grip-bug

### What did you expect to see?

The build passes the analysis phase.

### What did you see instead?

>ERROR: /home/jonathan/.cache/bazel/_bazel_jonathan/f698fe3e5b40978113a4dda16637f179/external/com_github_bmeg_grip/gripql/BUILD.bazel:24:11: no such target '@com_github_grpc_ecosystem_grpc_gateway//runtime:runtime': target 'runtime' not declared in package 'runtime' defined by /home/jonathan/.cache/bazel/_bazel_jonathan/f698fe3e5b40978113a4dda16637f179/external/com_github_grpc_ecosystem_grpc_gateway/runtime/BUILD.bazel and referenced by '@com_github_bmeg_grip//gripql:gripql'
>ERROR: /home/jonathan/.cache/bazel/_bazel_jonathan/f698fe3e5b40978113a4dda16637f179/external/com_github_bmeg_grip/gripql/BUILD.bazel:24:11: no such target '@com_github_grpc_ecosystem_grpc_gateway//utilities:utilities': target 'utilities' not declared in package 'utilities' defined by /home/jonathan/.cache/bazel/_bazel_jonathan/f698fe3e5b40978113a4dda16637f179/external/com_github_grpc_ecosystem_grpc_gateway/utilities/BUILD.bazel and referenced by '@com_github_bmeg_grip//gripql:gripql'

**Comment by jayconrod** [comment] 2020-09-18 18:16
Duplicate of #890

**Closed by jayconrod** 2020-09-18 18:16 UTC
