### ISSUE TITLE
Gazelle 0.22 breaks compatability with old rules_go

### ISSUE THREAD

**Issue by HALtheWise** [bazelbuild/bazel-gazelle#907] opened 2020-09-13 07:39 UTC
### What version of gazelle are you using?

`0.22.0`

### What version of rules_go are you using?

`0.21.0`

### What version of Bazel are you using?

`bazel 2.2.0`

### Does this issue reproduce with the latest releases of all the above?

No, updating rules_go fixes it, but the README implies gazelle should be compatible with the version I was using.

### What operating system and processor architecture are you using?

Linux amd64

### What did you do?

Try to compile a custom gazelle rule
`bazel run //tools/gazelle`

### What did you expect to see?

Success

### What did you see instead?

```
ERROR: .../tools/gazelle/BUILD.bazel:3:1: in gazelle_binary rule //tools/gazelle:gazelle_bin: 
Traceback (most recent call last):
        File ".../tools/gazelle/BUILD.bazel", line 3
                gazelle_binary(name = 'gazelle_bin')
        File "/home/.../.cache/bazel/_bazel_eric/2ced061487b1f09a502713c4b6fc9ffd/external/bazel_gazelle/internal/gazelle_binary.bzl", line 57, in _gazelle_binary_impl
                go.binary(go, <4 more arguments>)
        File "/home/.../.cache/bazel/_bazel_eric/2ced061487b1f09a502713c4b6fc9ffd/external/io_bazel_rules_go/go/private/actions/binary.bzl", line 41, in go.binary
                go.archive(go, source)
        File "/home/.../.cache/bazel/_bazel_eric/2ced061487b1f09a502713c4b6fc9ffd/external/io_bazel_rules_go/go/private/actions/archive.bzl", line 114, in go.archive
                emit_compilepkg(go, <10 more arguments>)
        File "/home/.../.cache/bazel/_bazel_eric/2ced061487b1f09a502713c4b6fc9ffd/external/io_bazel_rules_go/go/private/actions/compilepkg.bzl", line 61, in emit_compilepkg
                go.stdlib.libs
'NoneType' value has no field or method 'libs'
ERROR: Analysis of target '//tools/gazelle:gazelle' failed; build aborted: Analysis of target '//tools/gazelle:gazelle_bin' failed; build aborted
INFO: Elapsed time: 0.184s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (3 packages loaded, 17 targets configured)
FAILED: Build did NOT complete successfully (3 packages loaded, 17 targets configured)
```

It seems likely this is similar to bazelbuild/rules_go#2523, and caused by #804 @jayconrod

**Comment by jayconrod** [comment] 2020-09-14 18:28
Duplicate of #896. The fix should be backported to `v0.22.1` soon.

**Closed by jayconrod** 2020-09-14 18:28 UTC
