### ISSUE TITLE
cahed bazel_gazelle_go_repository_tools does not rebuild when OS architecture changes

### ISSUE THREAD

**Issue by jgao54** [bazelbuild/bazel-gazelle#1760] opened 2024-03-18 19:52 UTC
### What version of gazelle are you using?

v0.35.0

### What version of rules_go are you using?

v0.46.0

### What version of Bazel are you using?

7.0.2

### What operating system and processor architecture are you using?

linux x86-64/arm64

### What did you do?

We warm our CI jobs by pre-fetching a number of external dependencies in advance and downloading the prebuilt version just before job starts, including `bazel_gazelle_go_repository_tools`.

The `bazel_gazelle_go_repository_tools` dependency was fetched and built on a worker with linux x86 architecture and later when running a bazel command on a worker with linux arm architecture that contains this pre-built external dependency, the build fails rather than rebuild with the correct architecture. 

### What did you expect to see?

Build detects change in architecture and rebuild a compatible `bazel_gazelle_go_repository_tools` dependency; or have os-specific external dependencies (i.e. `bazel_gazelle_go_repository_tools_linux_x86` and `bazel_gazelle_go_repository_tools_linux_aarch64`)

### What did you see instead?

Build does not detect change in architecture, attempts to use the x86-compatible binary on arm, and fails with error:
```
ERROR: An error occurred during the fetch of repository 'com_github_google_go_containerregistry':
   Traceback (most recent call last):
	File "<path>/<to>/a6e8cb0ce75ceb1ea1faa0cca0b0ae0d/external/bazel_gazelle/internal/go_repository.bzl", line 254, column 17, in _go_repository_impl
		fail("failed to fetch %s: %s" % (ctx.name, result.stderr))
Error in fail: failed to fetch com_github_google_go_containerregistry:
```
This is because the tools built in @bazel_gazelle_go_repository_tools//:bin/* have an incompatible exec format and result in segfault.

**Comment by fmeum** [comment] 2024-03-20 09:27
As far as I understand we only use these binaries in the `go_repository` repo rule, which also runs on the host. Remote workers shouldn't be involved in any of this. Do you have a reproducer you could share?

**Comment by jgao54** [comment] 2024-03-21 23:54
@fmeum  My apologies on terminology, was thinking in terms of CI workers -- but these issues are happening on the host -- we are not using remote execution.

Our pre-warm strategy is to populate the output_base from a remote s3 location. This worked fairly well historically (albeit unconventional). However, when we introduced linux arm64 instances for ci jobs, we forgot the update the pre-warm logic, so the downloaded external deps are for linux x86 instead of linux arm64.

However, I would have expected bazel to detect the change in architecture -- and thus rebuild the external repository with the correct dependencies. Is this assumption flawed?

**Comment by fmeum** [comment] 2024-03-22 08:41
I would say this is expected: Sharing an output base between machines is not officially supported. https://github.com/bazelbuild/bazel/issues/12227 is actively being worked on and will provide a safe way of doing that.

Since I don't think that this is something that could be changed in Gazelle itself, I will close this issue. If you think that the issue linked above doesn't address your use case, I would suggest opening a feature request on the Bazel repo.

**Closed** 2024-03-22 08:41 UTC
