### ISSUE TITLE
Feature Request: update-repos -from_file=go.mod

### ISSUE THREAD

**Issue by robfig** [bazelbuild/bazel-gazelle#306] opened 2018-09-03 18:54 UTC
Are there any plans to make Gazelle able to update WORKSPACE to correspond to the contents of a go.mod file, for compatibility with Go 1.11 modules? 

If possible, I'd like to keep our codebase buildable by the Go command line tool after migration to Bazel, to retain the ability to use all of the development tools that are not bazel-aware (gocode, godef). Having go.mod be the source of truth and CI to verify that it was in sync with WORKSPACE seemed like it would be a good way to do it, while avoiding vendoring (we have a *lot* of dependencies). 

Thank you,
Rob

**Comment by jayconrod** [comment] 2018-09-04 18:54
I'm planning to support this, and I have a change which is about halfway ready. The challenge is that Gazelle can't simply read the go.mod file; it needs to run `go list -m`, which requires the go toolchain (may not be installed when run with `bazel run //:gazelle`), requires network access, and has side effects on the module cache. So I'd like to try to do this hermetically with reasonable performance if possible.

**Comment by jayconrod** [comment] 2018-09-04 18:54
Closing as a duplicate of #200.

**Closed by jayconrod** 2018-09-04 18:54 UTC
