### ISSUE TITLE
defaultModInfo does not work for certain import paths

### ISSUE THREAD

**Issue by siddharthab** [bazelbuild/bazel-gazelle#574] opened 2019-07-09 21:40 UTC
defaultModInfo uses the `go list` command to fetch module info, but the command does not produce correct results for certain import paths. For example,
```
$ go list -find -f '{{.Module.Path}}' -- v.io/v23/context
go: finding v.io/v23/context latest
go: finding v.io/v23 latest
go: downloading v.io/v23 v23.0.0-20190603052200-31f2bd66a7da
can't load package: package v.io/v23/context: unknown import path "v.io/v23/context": cannot find module providing package v.io/v23/context
```

**Comment by siddharthab** [comment] 2019-07-09 23:48
Note that this can be worked around if you use go_repository rules and specify `gazelle:repository_macro` directive or equivalent.

**Comment by jayconrod** [comment] 2019-07-10 13:56
I was able to reproduce this by unsetting `GOPROXY` or `GOPROXY=direct` in go1.13beta1. May be a bug in Go. I'll take a look.

**Comment by jayconrod** [comment] 2019-07-10 13:58
The package path is really confusing. I'd expect `v23` to be a semantic import version suffix, but it's not: the module path is `v.io`, and the latest version is `v0.1.3`. That's likely triggering a bug here.

**Comment by siddharthab** [comment] 2019-07-10 16:57
Thanks for looking into this.

This is not urgent because it will only trigger when people are not using the repository_macro directive.

**Comment by jayconrod** [comment] 2019-07-10 18:44
Confirmed this is a bug in `go list`. Thanks for reporting. I've opened golang/go#33035 to track it upstream.

I'll close this issue since I don't think there's anything for Gazelle to do differently.

**Closed by jayconrod** 2019-07-10 18:44 UTC
Labels: bug
