### ISSUE TITLE
proto plugin should support a library-per-file mode

### ISSUE THREAD

**Issue by wolfd** [bazelbuild/bazel-gazelle#1032] opened 2021-04-18 07:14 UTC
The docs for [`proto_library` state](https://docs.bazel.build/versions/master/be/protocol-buffer.html#proto_library) that the recommended organization is to make a `proto_library` rule for every file:

> Recommended code organization:
>
>  - One proto_library rule per .proto file.
>  - A file named foo.proto will be in a rule named foo_proto, which is located in the same package.
>  - A [language]_proto_library that wraps a proto_library named foo_proto should be called foo_[language]_proto, and be located in the same package.

Currently the only way to get more fine-grained `proto_library`s is to:
- move proto files around to different directories.
- use `package` mode and change package names for all proto files that you want to bundle differently.
- use `package` mode with `proto_group` option enabled, and add that option to your proto files.

I propose a new `file` mode for the proto plugin that follows the recommendations above. The rule name/grouping could still be overridden via an `option` like in `package` mode, if need be.

**Comment by jayconrod** [comment] 2021-05-26 21:07
Duplicate of #138

**Closed by jayconrod** 2021-05-26 21:07 UTC
