### ISSUE TITLE
Gazelle fails on repo with `.proto` file (test data) next to main.go

### ISSUE THREAD

**Issue by jmillikin-stripe** [bazelbuild/bazel-gazelle#255] opened 2018-07-03 21:21 UTC
https://github.com/ckaznocha/protoc-gen-lint has `main.go` and `test.proto` in the same directory, the latter being used as test data for manual tests.

Gazelle doesn't know how to deal with this:
```
$ gazelle -go_prefix github.com/ckaznocha/protoc-gen-lint .
gazelle: found packages main (main.go) and test () in /Users/jmillikin/src/protoc-gen-lint
```

**Comment by jayconrod** [comment] 2018-07-03 21:35
What version of gazelle are you using? At the tip of master, it generates rules without complaining, but it tries to embed the generated `go_proto_library` into the `go_library`, which won't build since they're actually different packages. Which is also a bug.

**Comment by jmillikin-stripe** [comment] 2018-07-03 23:13
This was with `@bazel_gazelle` at f4ae892927eeabd060c59693c38e82303f41558d -- I hadn't tried head.

**Comment by jayconrod** [comment] 2018-07-09 19:00
With #264 merged, this is mostly working as intended.

There is still some weirdness: the generated `go_library` will embed the generated `go_proto_library` because they have the same import path. The `go_proto_library` gets an inferred import path (same as the `go_library`) because `option go_package` does not specify it explicitly.

For this particular repo, since test.proto is a test file, it would be better to exclude it using `# gazelle:exclude test.proto`. We don't need rules to build it, but Gazelle won't know that automatically.

**Closed by jayconrod** 2018-07-09 19:00 UTC
Labels: bug, proto
