### ISSUE TITLE
go module replace to a relative path failed to update-repos

### ISSUE THREAD

**Issue by levimm** [bazelbuild/bazel-gazelle#685] opened 2019-12-23 08:07 UTC
### What version of gazelle are you using?
v0.19.1

### What version of rules_go are you using?
v0.20.2

### What version of Bazel are you using?
 0.28.1

### Does this issue reproduce with the latest releases of all the above?
yes

### What operating system and processor architecture are you using?
tried mac and ubuntu

### What did you do?
This is a monorepo with multiple go modules. Let's say I have two module `utils` and `client` and I have successfully built `utils` with bazel. Now I'm trying to build `client` and using following command to update go_repositories in WORKSPACE.
`bazel run //:gazelle -- update-repos -from_file=go.mod`
And the `client` module contains such replace directive.
`replace example.com/hello/utils => ../utils`

### What did you expect to see?
The rules are added successfully to WORKSPACE file in `client` module.

### What did you see instead?
go: example.com/hello/utils@v0.0.0-00010101000000-000000000000: parsing ../utils/go.mod: open /tmp/utils/go.mod: no such file or directory
gazelle: exit status 1

**Comment by jayconrod** [comment] 2020-01-02 16:17
Duplicate of #650

**Closed by jayconrod** 2020-01-02 16:17 UTC
