### ISSUE TITLE
Gazelle doesn't correct import deps with version (eg. v1) on them

### ISSUE THREAD

**Issue by cristiandonosoc** [bazelbuild/bazel-gazelle#849] opened 2020-07-29 00:07 UTC
Tom Lundell told me file this bug against gazelle.

### What version of Bazel are you using?

3.4.1

### What operating system and processor architecture are you using?

Windows 10 x64

### What did you do?
import(
secretmanager "cloud.google.com/go/secretmanager/apiv1"
)

### What did you expect to see?

deps = [
"@com_google_cloud_go//secretmanager/apiv1:secretmanager"
]

### What did you see instead?

deps = [
"@com_google_cloud_go//secretmanager/apiv1"
]

**Comment by tomlu** [comment] 2020-07-29 00:10
This happens when using `go_naming_convention=import`

**Comment by jayconrod** [comment] 2020-08-03 21:41
Is `@com_google_cloud_go//secretmanager/apiv1:secretmanager` actually the expected label for `cloud.google.com/go/secretmanager/apiv1`? In the current draft implementation, the name is derived only from the import path, not the package name, so I would expect `@com_google_cloud_go//secretmanager/apiv1` would be the correct label.

There is some handling for module major version suffixes (so `github.com/foo/bar/v2` would be `@com_github_foo_bar_v2//:bar`, not `@com_github_foo_bar_v2//:v2`), but that wouldn't apply to a suffix like `apiv1`.

**Comment by tomlu** [comment] 2020-08-03 21:49
Yeah OK, so the issue is that the external repo is wrong. We do not build an index into it, and its `BUILD` files do not match Gazelle's Glaze-like expectations?

**Comment by jayconrod** [comment] 2020-08-03 22:03
It doesn't look like that repository has build files checked in. Are they generated with Gazelle? If so, it's certainly a bug if the generated names are different than what external dependency resolution expects.

**Comment by tomlu** [comment] 2020-08-04 19:37
Yes, they are generated with Gazelle. It's probably a generation bug then rather than a resolution bug. I would turn my suspicious eye to the presumably dodgy code written by yours truly :)

**Comment by jayconrod** [comment] 2020-08-07 18:36
I just tested this with 570264c1, the tip of the `go_naming_convention` branch. When a library imports this package, the generated target looks like this:

```
go_library(
    name = "m",
    srcs = ["use.go"],
    importpath = "example.com/m",
    visibility = ["//visibility:public"],
    deps = ["@com_google_cloud_go//secretmanager/apiv1"],
)
```

The actual target is:

```
go_library(
    name = "apiv1",
    srcs = [
        "doc.go",
        "iam.go",
        "secret_manager_client.go",
    ],
    importpath = "cloud.google.com/go/secretmanager/apiv1",
    visibility = ["//visibility:public"],
    deps = [
        "//iam",
        "@com_github_golang_protobuf//proto:go_default_library",
        "@com_github_googleapis_gax_go_v2//:gax-go",
        "@go_googleapis//google/cloud/secretmanager/v1:secretmanager_go_proto",
        "@go_googleapis//google/iam/v1:iam_go_proto",
        "@org_golang_google_api//iterator",
        "@org_golang_google_api//option",
        "@org_golang_google_api//transport/grpc",
        "@org_golang_google_grpc//:go_default_library",
        "@org_golang_google_grpc//codes",
        "@org_golang_google_grpc//metadata",
    ],
)

alias(
    name = "go_default_library",
    actual = ":apiv1",
    visibility = ["//visibility:public"],
)
```

The library builds, so I think this is correct. Please confirm.

The target name comes from the last component of the import path. In this case, that's different from the package name (`secretmanager`). It's important that it works this way: when Gazelle resolves an import of an external library, it doesn't have access to the library's sources, so it can't look up the package name. Gazelle can only use the import path and some metadata about the external repo to derive the `deps` label.

**Comment by tomlu** [comment] 2020-08-07 18:52
This looks correct, thanks. The fix must have been in the delta between your version and yours (that build file was generated before you started working on it).

**Comment by jayconrod** [comment] 2020-08-07 19:00
Cool, thanks for checking. I'll close this.

PTAL at the `go_naming_convention` branch. I think it's basically ready to go. I'll send a PR to merge it to the main branch next week.

**Closed by jayconrod** 2020-08-07 19:00 UTC
