### ISSUE TITLE
Virtual target name collisions result in parsing errors

### ISSUE THREAD

**Issue by Helcaraxan** [bazelbuild/bazel-gazelle#954] opened 2020-11-10 18:12 UTC
### What version of gazelle are you using?

Issue reproduced on v0.22.0, v0.22.1 and v0.22.2, not on v0.21.1.

### What version of rules_go are you using?

Issue reproduced with both v0.24.3 and v0.24.6.

### What version of Bazel are you using?

3.7.0

### Does this issue reproduce with the latest releases of all the above?

Yes.

### What operating system and processor architecture are you using?

Reproduced on both Linux & OSX.

### What did you do?

I have BUILD.bazel files with two targets, one a `go_binary` rule, one a macro, with the same name. This is legal and supported by Bazel as long as the macro does not implicitly define a rule with the same name again.

### What did you expect to see?

Updating my project's BUILD.bazel files with Gazelle works as expected.

### What did you see instead?

An error reported about two rules with the same name in my BUILD.bazel file. This was not case up to and including Gazelle 0.21.1 but started to happen with the 0.22.0 release.

**NB: A full minimal repro of the issue can be found [here](https://github.com/Helcaraxan/gazelle_update_issue).**

**Comment by jayconrod** [comment] 2020-11-11 20:28
Thanks for putting together a repro and writing this. Made it easy to figure out what's going on.

It looks like this is new behavior from #855, a fix for #850, which is actually the opposite of this issue. So I suppose this is working as intended. (I completely forgot about this change; August seems like forever ago).

I think this is actually the right thing to do. Gazelle doesn't evaluate Starlark, so it can't distinguish between rules and macros. When two calls apparently have the same name, Gazelle can't tell which one to update, and it can't insert new targets. For example, even in `v0.21.1`, If you delete the `embed` attribute from `//main`, Gazelle won't restore it. It still fails to merge, but it does so silently.

Couple suggestions for workarounds:

* In the macro, use a parameter other than `name`.
* Declare the `go_binary` inside the macro and use `# gazelle:map_kind` to make Gazelle update the macro call.

Closing the issue, but happy to discuss further.

**Closed by jayconrod** 2020-11-11 20:28 UTC

**Comment by Helcaraxan** [comment] 2020-11-12 11:00
@jayconrod, thank you for the update. I understand the position and can indeed work around the issue.

FWIW, in our (more complex than the repro case) setup `v0.21.1` was still able to merge its updates with the appropriate `go_library` rule even if it then silently failed on the `go_binary` one. I agree that it's better to have an explicit failure, but the change in behaviour was unexpected. :+1:
