### ISSUE TITLE
fail if any import statements are unrecognised

### ISSUE THREAD

**Issue by asuffield** [bazelbuild/bazel-gazelle#622] opened 2019-08-19 13:12 UTC
It is regularly confusing to users when they run gazelle and it completes successfully, then the build fails because some import statement was not recognised and gazelle responded by just not including this dependency in the BUILD file. This is extra-double-confusing when the bug is a subtle misspelling in the import statement in the go code, because the error from bazel will be the mangled name, and you have to unmangle it to spot the mistake.

Please have a "strict" mode for gazelle which fails instantly if it sees an unrecognised import statement. I don't always want this for go_repository rules, but I do always want it for go code that I wrote.

**Comment by jayconrod** [comment] 2019-08-19 14:00
Duplicate of #499

**Closed by jayconrod** 2019-08-19 14:00 UTC
