### ISSUE TITLE
go:build syntax is not supported

### ISSUE THREAD

**Issue by ash2k** [bazelbuild/bazel-gazelle#1099] opened 2021-08-30 07:38 UTC
### What version of gazelle are you using?

v0.23.0

### What version of rules_go are you using?

v0.28.0

### What version of Bazel are you using?

v4.2.0

### Does this issue reproduce with the latest releases of all the above?

Yes.

### What operating system and processor architecture are you using?

macOS 11.5.2 amd64.

### What did you do?

Ran `go run golang.org/x/tools/cmd/goimports@v0.1.5` and it added a `go:build tools` directive. Then I removed the old one `+build tools`.

```go
//go:build tools          <- was added
// +build tools            <- I removed this one

package build

// https://github.com/golang/go/wiki/Modules#how-can-i-track-tool-dependencies-for-a-module

import (
	_ "github.com/golang/mock/mockgen"
	_ "golang.org/x/tools/cmd/goimports"
)
```

Then I ran gazelle.

### What did you expect to see?

No changes to build files.

### What did you see instead?

Gazelle updated the build file for this package - added a `go_library` target.

This seem to be new behavior, added in Go 1.17. Please see `//go:build lines` under https://golang.org/doc/go1.17#go-command.

**Comment by robfig** [comment] 2021-10-16 20:04
Confirmed - Gazelle does not recognize `//go:build` build tags. They are ignored.  The relevant code is here: `//language/go/fileinfo.go` in `readTags`.   It looks like the `go/build/constraint` package may be helpful to the implementation. 

Thanks for the report! Any interest in submitting a pull request?

**Comment by thempatel** [comment] 2022-04-19 17:06
I'll take this one if no one else wants it

**Comment by thempatel** [comment] 2022-04-25 18:29
@robfig pushed up a PR referencing this issue, still need to add some tests but could use some feedback on approach. There are some possibly breaking changes that we would need to discuss

**Comment by thempatel** [comment] 2022-05-08 14:49
@achew22 fyi we still need to land #1243 before we can close this issue

**Closed** 2022-07-17 04:08 UTC
Labels: help-wanted
