### ISSUE TITLE
language/go: generated platforms not declared in rules_go v0.22.4

### ISSUE THREAD

**Issue by johanbrandhorst** [bazelbuild/bazel-gazelle#780] opened 2020-05-14 09:39 UTC
### What version of gazelle are you using?

`v0.21.0`

### What version of rules_go are you using?

`v0.22.4`

### What version of Bazel are you using?

`v3.1.0`

### Does this issue reproduce with the latest releases of all the above?

No, it works fine with `rules_go` `v0.23.0`

### What operating system and processor architecture are you using?

Linux x86_64

### What did you do?

Try running `bazel test //...` in the grpc-gateway with the aforementioned versions.

### What did you expect to see?

A successful test result.

### What did you see instead?

A strange platform error:
```
ERROR: Analysis of target '//examples/internal/cmd/example-gateway-server:example-gateway-server' failed; build aborted: no such target '@io_bazel_rules_go//go/platform:illumos': target 'illumos' not declared in package 'go/platform' defined by /<REDACTED>/.cache/bazel/_bazel_<REDACTED>/139d5bd62b3cea2b9ba60fa30fdc515d/external/io_bazel_rules_go/go/platform/BUILD.bazel
```
Also sometimes a slightly different one:
```
ERROR: Analysis of target '//examples/internal/cmd/example-gateway-server:go_default_library' failed; build aborted: no such target '@io_bazel_rules_go//go/platform:aix': target 'aix' not declared in package 'go/platform' defined by /root/.cache/_grpc_gateway_bazel/external/io_bazel_rules_go/go/platform/BUILD.bazel
```

### Other information

gRPC-Gateway PR: https://github.com/grpc-ecosystem/grpc-gateway/pull/1325.

CI build log: https://app.circleci.com/pipelines/github/grpc-ecosystem/grpc-gateway/446/workflows/d4c32cae-7b95-4560-9d42-b71755288817/jobs/9025/steps.

I have a feeling this is a simple incompatibility between `gazelle` `v0.21.0` and the older `rules_go` `v0.22.4`. If so, that is disappointing, as it will mean our master branch will not be able to use newer versions of `gazelle`, since we've committed to staying on `v1.3.x` of `golang/protobuf` for backwards compatibility reasons, and `rules_go` `v0.23.0` is incompatible with that choice (see errors: https://github.com/grpc-ecosystem/grpc-gateway/pull/1326).

**Comment by jayconrod** [comment] 2020-05-18 15:03
Sorry for the slow response. Last week was a busy week, and I'm still catching up.

This is indeed an incompatibility between Gazelle `v0.21.0` and rules_go `v0.22.x`. I had forgotten about this and should have mentioned it in the release notes. There were a number of `GOOS` / `GOARCH` pairs missing from rules_go, so I added those and added support for generating rules that use them to Gazelle. But that means build files generated with Gazelle `v0.21.0` may not work with versions of rules_go before `v0.23.0`.

This could probably be fixed though. The Go extension could look up the version of rules_go being used and could make sure to generate rules compatible with that.

**Comment by johanbrandhorst** [comment] 2020-05-28 20:30
I updated to 0.21.1, and I'm not sure if this was supposed to be fixed, but now I'm getting an even stranger error:

```
ERROR: Analysis of target '//examples/internal/cmd/example-gateway-server:go_default_library' failed; build aborted: Analysis failed
```
See https://app.circleci.com/pipelines/github/grpc-ecosystem/grpc-gateway/731/workflows/f0e51a39-607d-4b21-a9ae-07e873288818/jobs/11272/steps for more information, but there's not much more there. Running it locally results in similar errors (note the different target, it appears to vary):
```
$ bazel test //...
ERROR: Analysis of target '//examples/internal/helloworld:go_default_library' failed; build aborted: Analysis failed
INFO: Elapsed time: 0.328s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (0 packages loaded, 17 targets configured)
FAILED: Build did NOT complete successfully (0 packages loaded, 17 targets configured)
    Fetching @org_golang_x_sys; fetching
```

**Comment by johanbrandhorst** [comment] 2020-07-22 17:23
Still getting strange errors in the grpc-gateway with new versions of bazel_gazelle:
```
Analyzing: 62 targets (51 packages loaded, 700 targets configured)

INFO: Repository remote_java_tools_linux instantiated at:

  no stack (--record_rule_instantiation_callstack not enabled)

Repository rule http_archive defined at:

  /root/.cache/_grpc_gateway_bazel/external/bazel_tools/tools/build_defs/repo/http.bzl:336:31: in <toplevel>

INFO: Repository remotejdk11_linux instantiated at:

  no stack (--record_rule_instantiation_callstack not enabled)

Repository rule http_archive defined at:

  /root/.cache/_grpc_gateway_bazel/external/bazel_tools/tools/build_defs/repo/http.bzl:336:31: in <toplevel>

ERROR: Analysis of target '//examples/internal/integration:go_default_test' failed; build aborted: Analysis failed

INFO: Elapsed time: 2.324s

INFO: 0 processes.

FAILED: Build did NOT complete successfully (100 packages loaded, 1082 targets configured)

ERROR: Couldn't start the build. Unable to run tests

FAILED: Build did NOT complete successfully (100 packages loaded, 1082 targets configured)
```
See https://app.circleci.com/pipelines/github/grpc-ecosystem/grpc-gateway/734/workflows/6d9782fd-69f9-4d4a-961f-ccea6064c2cf/jobs/11301 and https://github.com/grpc-ecosystem/grpc-gateway/pull/1325.

**Comment by jayconrod** [comment] 2020-07-22 18:28
Thanks for pinging this. I'll reopen the issue. Probably won't have bandwidth to fix it for a couple weeks though.

I tried to reproduce this. The Bazel messages are extremely unhelpful in finding the problem. It looks like `@org_golang_google_grpc//internal/syscall:go_default_library` still refers to platforms in newer rules_go versions. So the Gazelle fix for this issue is not working correctly.

**Comment by jayconrod** [comment] 2020-09-11 20:31
Sorry it's taken me so long to get back to this. I think #905 should fix it. Let me know if that works, and I can do a patch release soon.

**Closed** 2020-09-11 20:30 UTC
Labels: bug
