### ISSUE TITLE
mode=diff does not respect missing/empty files

### ISSUE THREAD

**Issue by vpanta** [bazelbuild/bazel-gazelle#925] opened 2020-10-01 20:03 UTC
### What version of gazelle are you using?

v0.22.0

### What version of rules_go are you using?

v0.24.2

### What version of Bazel are you using?

3.1.0

### Does this issue reproduce with the latest releases of all the above?

yes

### What operating system and processor architecture are you using?

macOS Catalina, 10.15.7, x64

### What did you do?

I ran `bazel run :gazelle` followed by `bazel run :gazelle -- -mode=diff`

Or alternatively, I changed the `gazelle()` target to include `args = ["-mode=diff"]` and re-ran for the second command. I attempted both ways.

### What did you expect to see?

No output from diff and a success code, as I'd just fixed the BUILD files according to gazelle.

### What did you see instead?

Diffs, including empty `BUILD.bazel` files showing a diff of just a newline, and an error code.
I had hoped to use `-mode=diff` as a precommit, but as it returns unexpected diffs, I cannot.

**Comment by vpanta** [comment] 2020-10-01 20:46
So I've been looking further, and it actually seems like all the diffs are files it decided need to exist with a single newline in them, but don't currently exist.

I think it's a result of https://github.com/bazelbuild/bazel-gazelle/commit/70f8ccb87fe70445ca036e31ab9b892e03f56081 removing
```go
diff.A = difflib.SplitLines(string(oldContent))
```
 when the file is not found, but still using
```go
diff.B = difflib.SplitLines(string(newContent))
```
[As `SplitLines` seems to turn an empty string into `[]string{"\n"}`](https://github.com/pmezard/go-difflib/blob/5d4384ee4fb2527b0a1256a821ebfc92f91efefc/difflib/difflib.go#L768)

**Comment by vpanta** [comment] 2020-10-01 21:13
I just put that out as a prospective fix. Let me know if it's worthwhile or if you'd rather we take this a different direction.

**Comment by jayconrod** [comment] 2020-10-02 15:40
I think this is a duplicate of #853.

**Closed by jayconrod** 2020-10-02 15:40 UTC

**Comment by vpanta** [comment] 2020-10-02 15:50
Ah, it is, the title there is misleading, because these files are missing and diff-mode is actually saying they should exist but be empty.
