### ISSUE TITLE
Gazelle creates all target with name go_default_library

### ISSUE THREAD

**Issue by PradeepJigalur** [bazelbuild/bazel-gazelle#770] opened 2020-05-05 06:52 UTC
v0.20.0

v0.22.4

### Does this issue reproduce with the latest releases of all the above?

NA

### What operating system and processor architecture are you using?

CentOs

### What did you do?

my Ex project is like this

test/
       test.go

when I run gazelle it created BUILD.bazel file and the target it has is

go_library(
    name = "go_default_library"}

### What did you expect to see?

go_library(
    name = "test"}

### What did you see instead?
go_library(
    name = "go_default_library"}

**Comment by jayconrod** [comment] 2020-05-05 12:50
Duplicate of #5

**Closed by jayconrod** 2020-05-05 12:50 UTC
