### ISSUE TITLE
Add support for `WORKSPACE.bazel` file

### ISSUE THREAD

**Issue by Kiougar** [bazelbuild/bazel-gazelle#810] opened 2020-06-09 15:15 UTC
The following line causes a failure if the `WORKSPACE` file is named as `WORKSPACE.bazel`.

https://github.com/bazelbuild/bazel-gazelle/blob/cc925457395c4b962856a31d0f7a3858657dc2fc/deps.bzl#L48

Related issues:
* bazelbuild/rules_docker#1487
* bazelbuild/bazel#11036

**Comment by jayconrod** [comment] 2020-06-15 17:20
Closing as a duplicate of #678.

**Closed by jayconrod** 2020-06-15 17:20 UTC
Labels: bug, repos
