### ISSUE TITLE
gazelle fails to include required dependencies

### ISSUE THREAD

**Issue by apesternikov** [bazelbuild/bazel-gazelle#518] opened 2019-05-02 18:48 UTC
looks like there is a corner case failure, when imported package name is clashing with its own package name. For example:
the following code
```go
package v1

import (
        v1 "other/package/v1"
)
```
generates BUILD file without reference to bazel package implementing `other/package/v1` in deps

to reproduce: 
clone `https://github.com/apesternikov/gazelle-repro`
`bazel build //:go_default_library`

package @com_github_census_instrumentation_opencensus_proto//gen-go/metrics/v1:go_default_library does not compile:
```
compile: missing strict dependencies:
	/private/var/tmp/_bazel_pesterni/50726d5162b6b218b7d25c056baa59c0/sandbox/darwin-sandbox/1/execroot/__main__/external/com_github_census_instrumentation_opencensus_proto/gen-go/metrics/v1/metrics.pb.go: import of "github.com/census-instrumentation/opencensus-proto/gen-go/resource/v1"
Known dependencies are:
	github.com/golang/protobuf/proto
	github.com/golang/protobuf/ptypes/timestamp
	github.com/golang/protobuf/ptypes/wrappers
Check that imports in Go sources match importpath attributes in deps.
```
a patch to several BUILD files is required to make it compile. Uncomment the commented line to apply patch
https://github.com/apesternikov/gazelle-repro/blob/1e9e5318c87c01092b9231a9295602394f1cf2d5/WORKSPACE#L29

The same code is compiling successfully by
`go build`

**Comment by jayconrod** [comment] 2019-05-03 21:09
I think this is a duplicate of #498. See [this comment](https://github.com/bazelbuild/bazel-gazelle/issues/498#issuecomment-486387509) for workarounds.

**Closed by jayconrod** 2019-05-03 21:09 UTC
